language: node_js
node_js:
  - "5"
  - "6"
  - "7"

cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli

install:
  - git clone --branch example https://github.com/giuem/hexo-theme-agnes.git build
  - mkdir -p build/themes/agnes
  - mv !(build) build/themes/agnes
  - cd build
  - npm install

# before_script:
#   - cd build

script:
  - hexo cl
  - hexo g

after_script:
  - cd ./public
  - git init
  - git add .
  - git commit -m "Auto build by Travis CI."
  - git config user.name "giuem"
  - git config user.email "$GIT_EMAIL"
  - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/giuem/hexo-theme-agnes.git" master:gh-pages

