language: node_js
node_js:
  - "5"
  - "6"
  - "7"

cache:
  directories:
    - node_modules

install:
  - npm install
  - git clone https://github.com/giuem/hexo-theme-agnes.git themes/agnes

script:
  - hexo cl
  - hexo g

after_script:
  - cd ./public
  - git init
  - git add .
  - git commit -m "Auto build by Travis CI."
  - git config user.name "giuem"
  - git config user.email "$GIT_EMAIL"
  - git push --force --quiet "git@github.com:giuem/hexo-theme-agnes.git" master:gh-pages

