head:
  title_separate: "|"
  favicon: favicon.ico
  rss: atom.xml

header:
  nav:
    Link: "/hexo-theme-agnes/link"
    Archive: "/hexo-theme-agnes/archives"
    About: "/hexo-theme-agnes/about"

footer:
  since:

comment:
  disqus:
